#key=value
#\uC694\uCCADURL=\uBAA8\uB378 \uD074\uB798\uC2A4
/list.do=kr.board.action.ListAction
/writeForm.do=kr.board.action.WriteFormAction
/write.do=kr.board.action.WriteAction
/detail.do=kr.board.action.DetailAction
/modifyForm.do=kr.board.action.ModifyFormAction
/modify.do=kr.board.action.ModifyAction
/deleteForm.do=kr.board.action.DeleteFormAction
/delete.do=kr.board.action.DeleteAction